// CurrentAddress
export const CHANGE_LOCATION = 'CHANGE_LOCATION'

//Initial Location Updates
export const INITIAL_LAT = 'INITIAL_LAT'
export const INITIAL_LNG = 'INITIAL_LNG'
export const INITIAL_REGION = 'INITIAL_REGION'

// Register
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER'
export const UPDATE_PHONE_WITH_CODE = 'UPDATE_PHONE_WITH_CODE'
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL' 
export const UPDATE_LICENCE_NUMBER = 'UPDATE_LICENCE_NUMBER'
export const UPDATE_DATE_OF_BIRTH = 'UPDATE_DATE_OF_BIRTH'
export const UPDATE_REFERRAL_CODE = 'UPDATE_REFERRAL_CODE'

//Speciality Details
export const UPDATE_SPECIALITY_NAME = 'UPDATE_SPECIALITY_NAME'
export const UPDATE_SPECIALITY_BRAND = 'UPDATE_SPECIALITY_BRAND'
export const UPDATE_SPECIALITY_COLOR = 'UPDATE_SPECIALITY_COLOR'
export const UPDATE_SPECIALITY_NUMBER = 'UPDATE_SPECIALITY_NUMBER'
export const UPDATE_SPECIALITY_TYPE = 'UPDATE_SPECIALITY_TYPE'
export const UPDATE_SPECIALITY_TYPE_LBL = 'UPDATE_SPECIALITY_TYPE_LBL'



//Paypal Status
export const PAYPAL_PAYMENT_STATUS = 'PAYPAL_PAYMENT_STATUS'